# -------------------------------
# MapProxy configuration.
#
# OSM example based on https://wiki.openstreetmap.org/wiki/MapProxy
# this takes the osm and reprojects it to the belgium coordinate system EPSG:31370
# belgium bounds are used
# -------------------------------
services:
  demo:
  wmts:
    kvp: true
    restful: true
  wms:
    # only offer WMS 1.1.1
    versions: ['1.1.1']
    # supported SRS for this WMS
    srs: ['EPSG:900913','EPSG:31370']
    bbox_srs:
      - 'EPSG:900913'
      - srs: 'EPSG:31370'
        bbox: [14637.25,22608.21,291015.29, 246424.28]
    # limit the supported image formats.
    image_formats: ['image/png']

layers:
  - name: osm
    title: Open Streetmap Tiles
    sources: [osm_cache]
  - name: osm-be
    title: Open Streetmap Tiles Belgie
    sources: [osm_be_cache]    

caches:
  osm_cache:
    sources: [osm_tiles]
    grids: [GLOBAL_MERCATOR]
    format: image/png
    cache:
      type: geopackage
      filename: /srv/mapproxy/cachedata/osm.gpkg
      table_name: osm_tiles
  osm_be_cache:
    sources: [osm_cache] 
    grids: [belgiumgrid] 

sources:
  osm_tiles:
    type: tile
    url: http://c.tile.openstreetmap.org/%(tms_path)s.%(format)s
    grid: osm_grid 

grids:
  osm_grid:
    srs: EPSG:900913
    origin: nw
  belgiumgrid:
    srs: EPSG:31370 
    bbox: [2.5,49.5,6.4,51.51]
    bbox_srs: EPSG:4326
    origin: 'nw'
  belgium:
    base: GLOBAL_WEBMERCATOR
    srs: EPSG:31370 
    bbox: [2.5,49.5,6.4,51.51]
    bbox_srs: EPSG:4326
    origin: 'nw'   

globals:
  cache:
    base_dir: '/srv/mapproxy/cache'
    lock_dir: '/srv/mapproxy/cache/locks'
    tile_lock_dir: '/srv/mapproxy/cache/tile_locks'

  image:
      resampling_method: bilinear
      jpeg_quality: 90